### PR TITLE
Resolves #19

### LINKED ISSUE #19: Compilation error caused by implicit type conversion from String to int
When I do a clean and compile operation, I'm getting a couple of compilation errors:

```
[INFO] Compiling 22 source files to C:\Users\tom\Development\Java\git\ApexUnit\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Users\tom\Development\Java\git\ApexUnit\src\main\java\com\sforce\cd\apexUnit\client\connection\ConnectionHandler.java:[118,92] error: incompatible types: String cannot be converted to int
[ERROR] \Users\tom\Development\Java\git\ApexUnit\src\main\java\com\sforce\cd\apexUnit\client\connection\ConnectionHandler.java:[185,91] error: incompatible types: String cannot be converted to int
```

I believe the type of proxyPort property in CommandLineArguments.java should be changed from a String to an Integer, because the value for the proxy port argument passed to the ConnectionConfig.setProxy method is expected to be an int, and String cannot be implicitly converted to int.

### PR DESCRIPTION
**Pull request by tfuda**
Resolves #19 by fixing a compilation error due to code trying to do implicit conversion from String to int.

### CODE REVIEW

**Comment by adarsh-ramakrishna-sfdc** [comment]
Thanks @tfuda . This resolves the issue. 
All tests passed. pull request looks good to merge.
@vamshi-sfdc  Do you want to take a look and merge the PR?

**Comment by vamshi-sfdc** [comment]
:+1:

**Comment by vamshi-sfdc** [comment]
@adarsh-ramakrishna-sfdc too bad to see issues with compilation errors. Not the productive use of time. Please set up autobuild and regression on jenkins.

Going forward no pull request to be signed off without passing CI

**Comment by vamshi-sfdc** [comment]
thanks @tfuda

**Comment by adarsh-ramakrishna-sfdc** [comment]
Yes @vamshi-sfdc . CI has been setup .. Auto builds and tests will be executed for each checkin on jenikns . IT CD team will be notified via email

**Pull request merged**
