### PR TITLE
fix for issue #12 added option to select triggers

### PR DESCRIPTION
**Pull request by leboff**
fix for #12 added a parameter to fetchApexClassesBasedOnMultipleRegexes  fetchApexClassesBasedOnRegex to specify whether triggers should be included in the query so that the query for test classes would not retrieve any triggers.

### CODE REVIEW

**Comment by vamshi-sfdc** [comment]
Thanks @leboff for the pull request. Can you please confirm if you have signed a CLA with salesforce.com?

**Comment by leboff** [comment]
I have not

**Comment by vamshi-sfdc** [comment]
Can you please send your CLA? The instructions are available at https://github.com/forcedotcom/ApexUnit/wiki/Contribution-and-Bug-Issue-tracking

**Comment by pmedapuram** [comment]
Thank you @leboff once again. I have reviewed the PR. Here is my :+1:

**Pull request merged**
