### PR TITLE
Changes related to the issues #61 and #62 plus 2 new build parameters to control the success conditions in CI tools

### PR DESCRIPTION
**Pull request by eSh3m4**
First I kept robymathew/ApexUnit@12fc46c solution of the issue [#62](https://github.com/forcedotcom/ApexUnit/issues/62)  and [#61](https://github.com/forcedotcom/ApexUnit/issues/61) over mine and merged it with the solution of similar ones provided in the 2.6.8 release. 

Then I solved the reporting issues introduced by those fixes as the computations where chunked in several calls and batches but not reconciled when having more than 200 tests (2075 tests methods in my case 🥇).

Finally I have added a time based report directory and two new optional parameters to fine tune the build outcomes when the scripts are in a Continuous integration cycle when for instance you are only interested in the reports but don't want to block the build chain.

//TODO : parametrize the time based report directory in order to keep the evolution seamless for current users

### CODE REVIEW

**Comment by robymathew** [comment]
HI - any update on this? These fixes would allow my team to move off our personal fork and back onto the main repo

**Comment by vamshi-sfdc** [comment]
@eSh3m4 can you please resolve the conflicts and have your changes pass the travis CI?

I have assigned @dragon0556 to help you with code review

**Comment by dragon0556** [comment]
@eSh3m4 Can you please work on conflicts. It seems that, you have old .travis.yml file. Due to this travis CI is failing. I would be greate if you merge latest master into your branch and remove the conflicts.

**Comment by eSh3m4** [comment]
Hi - Not quite sure of the direction regarding build results, I am reopening the PR and let you decide :) 
Thank you all for this powerful tool!

**Pull request closed without merging**
